# Generated by Django 5.2.3 on 2025-06-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='protocol',
            name='icon',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
