[phases.setup]
nixPkgs = [ 
  "python3",
  "python3Packages.pip",
  "mariadb-connector-c", 
  "pkg-config",
  "gcc",
  "python3Packages.python3",
  "python3Packages.setuptools",
  "python3Packages.wheel"
  
 ]

[phases.build]
commands = [
  "pip install -r requirements.txt"
]
