[phases.setup]
nixPkgs = [ 
  "python3",
  "python3Packages.pip",
  "mysql" 
 ]

[phases.build]
commands = [
  "python3 -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install -r requirements.txt"
]
